// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZ1aQ-WpM1gUiTjCs-IcnePAxfaszPVc',
    appId: '1:129179530930:web:be6e2a22f50142adb03bab',
    messagingSenderId: '129179530930',
    projectId: 'waiters-wallet',
    authDomain: 'waiters-wallet.firebaseapp.com',
    storageBucket: 'waiters-wallet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0uwJpTZFZlRasNPSuK7mbAnXhHHkEqjY',
    appId: '1:129179530930:android:7eea57ea0c72ec17b03bab',
    messagingSenderId: '129179530930',
    projectId: 'waiters-wallet',
    storageBucket: 'waiters-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZe4mkZwDuA6oP7kKrSbpMFLNWjVO_JuY',
    appId: '1:129179530930:ios:3b4b0b64b5ca1b20b03bab',
    messagingSenderId: '129179530930',
    projectId: 'waiters-wallet',
    storageBucket: 'waiters-wallet.appspot.com',
    iosBundleId: 'com.example.waitersWallet',
  );
}
